### ISSUE TITLE
Fatal Error when StringWrapper/Intl:strlen is passed null (BC break in 3.4.0)

### ISSUE THREAD

**Issue by ittmann** [laminas/laminas-stdlib#29] opened 2021-07-05 22:12 UTC
In 3.4.0 (because/after `declare(strict_types=1)` was added) when null is passed to StringWrapper/Intl:strlen a Fatal Error is thrown.
This was not the case in previous versions (up to 3.3.1)

`PHP Fatal error:  Uncaught TypeError: grapheme_strlen() expects parameter 1 to be string, null given in /application/vendor/laminas/laminas-stdlib/src/StringWrapper/Intl.php:55`

For example (in our case) it is triggered in an application using laminas-mvc-console when `php public/index.php` is run without arguments (this normally displays usage information)
```
PHP Fatal error:  Uncaught TypeError: grapheme_strlen() expects parameter 1 to be string, null given in /application/vendor/laminas/laminas-stdlib/src/StringWrapper/Intl.php:55
Stack trace:
#0 /application/vendor/laminas/laminas-stdlib/src/StringWrapper/Intl.php(55): grapheme_strlen(NULL)
#1 /application/vendor/laminas/laminas-mvc-console/src/View/RouteNotFoundStrategy.php(397): Laminas\Stdlib\StringWrapper\Intl->strlen(NULL)
#2 /application/vendor/laminas/laminas-mvc-console/src/View/RouteNotFoundStrategy.php(344): Laminas\Mvc\Console\View\RouteNotFoundStrategy->renderTable(Array, 3, 237)
#3 /application/vendor/laminas/laminas-mvc-console/src/View/RouteNotFoundStrategy.php(153): Laminas\Mvc\Console\View\RouteNotFoundStrategy->getConsoleUsage(Object(Laminas\Console\Adapter\Posix), 'index.php', Object(Laminas\ModuleManager\ModuleManager))
#4 /application/vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Laminas\Mvc\Console\View\RouteNotFoundStrategy->handleRouteNotFoundError(Object(Laminas\Mvc\MvcEvent))
#5 /applic in /application/vendor/laminas/laminas-stdlib/src/StringWrapper/Intl.php on line 55
```

**Comment by Ocramius** [comment] 2021-07-05 22:14
These operations require string input as per API signature?

**Comment by ittmann** [comment] 2021-07-05 22:16
> These operations require string input as per API signature?

grapheme_strlen does, but StringWrapper/Intl:strlen didn't before / without the strict_types it didn't throw an error

**Comment by Ocramius** [comment] 2021-07-05 22:21
It always did:
https://github.com/laminas/laminas-stdlib/blob/e89c2268c9cad25099f562f7f015c28c5dd383c9/src/StringWrapper/Intl.php

See the ***@***.*** string`?

**Comment by ittmann** [comment] 2021-07-05 22:27
> It always did

yes, but without the `declare(strict_types=1)` introduced in 3.4.0 `grapheme_strlen(null)` returns (int) 0

**Comment by Ocramius** [comment] 2021-07-05 22:32
Closing as duplicate of https://github.com/laminas/laminas-escaper/issues/20

**Closed as completed by Ocramius** 2021-07-05 22:32 UTC
Labels: Bug, Duplicate, Invalid
